apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  finalizers:
    - resources-finalizer.jrang188.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jrang188/my-k8s-configs.git
    path: charts/argo-cd/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true   
